# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Math.code
tagline:          'Data &amp; and Computer Science, Hadoop, ElasticSearch, Solr, Magento, Node.js...'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://mathieunls.github.io
baseurl:          /

author:
  name:           'Math.code'
  url:            https://twitter.com/MathieuNls

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:          https://github.com/MathieuNls/mathieunls.github.io
