# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        "/:title"

# Setup
title:            Mathieu Nayrolles' Blog
tagline:          'Data &amp; and Computer Sciences, Hadoop, ElasticSearch, Solr, Magento, Node.js, Xamarin, CI and more...'
description:      'Hi there ! I am Mathieu Nayrolles, Ph.D student <a href="https://twitter.com/Concordia">@Concordia</a>, co-founder of <a href="https://twitter.com/MindUpOfficial">@Mindup</a> &amp; <a href="https://twitter.com/ToolwatchApp">@Toolwatch</a> and published <a href="/books.html">author</a>. <div class="circular"></div><br /> Follow me <a href="https://twitter.com/MathieuNls">@MathieuNls</a> or <a href="http://eepurl.com/bu-Kt1">subscribe</a> for daily posts on Data &amp Computer Sciences, Hadoop, ElasticSearch, Solr, Magento, Node.js, Xamarin, CI and more...'
url:              http://mathieunls.github.io
baseurl:          /

author:
  name:           'Math.code'
  url:            https://twitter.com/MathieuNls

paginate:         10

github:
  repo:          https://github.com/MathieuNls/mathieunls.github.io

excerpt_separator: "<!--more-->"

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Mathieu L. Nayrolles"
resume_title:                   "Electrical and Computer Engineering Ph.D Student, Computer Science Lecturer, Author, Entrepreneur"
resume_contact_email:
  "mathieu.nayrolles@gmail.com"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/MathieuNls/"
  resume_twitter_url:           "http://twitter.com/MathieuNls"
  #resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/mathieun"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "https://math.co.de"

# Design settings
resume_theme:                   default

# Gems
#gems: [jekyll-paginate]
