# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        "/:title"

# Setup
title:            Mathieu Nayrolles' Blog
tagline:          'Data &amp; and Computer Sciences, Hadoop, ElasticSearch, Solr, Magento, Node.js, Xamarin, CI and more...'
description:      'Hi there ! I am Mathieu Nayrolles, Ph.D student <a href="https://twitter.com/Concordia">@Concordia</a>, co-founder of <a href="https://twitter.com/MindUpOfficial">@Mindup</a> &amp; <a href="https://twitter.com/ToolwatchApp">@Toolwatch</a> and published <a href="/books.html">author</a>. <div class="circular"></div><br /> Follow me <a href="https://twitter.com/MathieuNls">@MathieuNls</a> or <a href="http://eepurl.com/bu-Kt1">subscribe</a> for daily posts on Data &amp Computer Sciences, Hadoop, ElasticSearch, Solr, Magento, Node.js, Xamarin, CI and more...'
url:              http://mathieunls.github.io
baseurl:          /

author:
  name:           'Math.code'
  url:            https://twitter.com/MathieuNls

paginate:         10

github:
  repo:          https://github.com/MathieuNls/mathieunls.github.io

excerpt_separator: "<!--more-->"

# Gems
gems: [jekyll-paginate]
